name: cricket_india_game
description: A simple 2D cricket game made in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  flutter:
  assets:
    - assets/logo.png
    - assets/hit.mp3
    - assets/cheer.mp3
